site_name: ACME
theme:
  name: material
nav:
    - Quickstart: 'index.md'
    - Problem Description: 'problem.md'
    - Architecture: 'architecture.md'
    - Approach & Methodology: 'approach_methodology.md'
    - Install Manually: 'install_manually.md'